server {
    listen 80;
    server_name _;

    location /bitstoday-media/ {
        alias /usr/share/nginx/html/;
        autoindex off;
        add_header Cache-Control "public, max-age=3600";
        add_header X-Content-Type-Options "nosniff";
    }

    location / {
        return 404;
    }
}
